# Generated by Django 5.2.7 on 2026-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadormunicipal',
            name='operador_activo',
            field=models.BooleanField(default=True),
        ),
    ]
