# Generated by Django 5.2.7 on 2026-04-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_operadormunicipal_operador_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_subarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Sub-Área Activa?')),
                ('area_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='users.area')),
            ],
            options={
                'verbose_name': 'Sub-Área',
                'verbose_name_plural': 'Sub-Áreas',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'area_padre')},
            },
        ),
        migrations.AddField(
            model_name='operadormunicipal',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='users.subarea'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos', to='users.subarea'),
        ),
    ]
