# Generated by Django 5.2.7 on 2026-05-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subarea_operadormunicipal_subarea_puesto_subarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterField(
            model_name='area',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Área Activa'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='area_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='users.area', verbose_name='Área Superior'),
        ),
    ]
