# Generated by Django 5.2.7 on 2026-06-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_area_options_alter_area_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
