# Generated by Django 5.2.7 on 2026-01-16 11:09

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialActividadEvento',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('tabla', models.CharField(default='EVENTOS', max_length=50, verbose_name='Módulo')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('info_operador', models.TextField(verbose_name='Detalles del Movimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historial de Actividades',
                'db_table': 'historial_actividad_evento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.area')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.operadormunicipal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
