# Generated by Django 5.2.7 on 2026-01-16 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
