# Generated by Django 5.2.7 on 2026-01-16 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_eventos_fecha_publicacion_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
