# Generated by Django 5.2.7 on 2026-01-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_contacto_fecha_creacion_contacto_fecha_modificacion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='users.area'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='users.puesto'),
        ),
    ]
