# Generated by Django 5.2.7 on 2026-01-16 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_contacto_area_alter_contacto_puesto'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contactos/'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='ultima_modificacion_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_portal', to='users.area'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_portal', to='users.puesto'),
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='contactos',
        ),
    ]
