# Generated by Django 5.2.7 on 2026-02-11 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_contacto_creado_por_contacto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Evento'),
        ),
    ]
