# Generated by Django 5.2.7 on 2026-03-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_noticia_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto del Portal', 'verbose_name_plural': 'Contactos del Portal'},
        ),
    ]
