# Generated by Django 5.2.7 on 2026-03-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_contacto_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo_portal', models.CharField(help_text='Ej: Sector de Rentas', max_length=200)),
                ('subtitulo_portal', models.CharField(help_text='La frase que va debajo del título', max_length=255)),
                ('texto_boton', models.CharField(default='Ver Agenda', max_length=50)),
                ('url_destino', models.CharField(blank=True, max_length=100)),
                ('color_destacado', models.CharField(default='#1a2a40', help_text='Color en formato HEX', max_length=7)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_web', to='users.area')),
            ],
            options={
                'verbose_name': 'Configuración de Sector',
                'db_table': 'configuracion_sectores',
            },
        ),
    ]
