# Generated by Django 5.2.7 on 2026-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_configuracionsector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsector',
            options={'verbose_name': 'Configuración de Sector', 'verbose_name_plural': 'Configuraciones de Sectores'},
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='color_iconos',
            field=models.CharField(default='#1a2a40', help_text='Color para iconos de dependencias y bordes (HEX)', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='color_texto_principal',
            field=models.CharField(default='#ffffff', help_text='Color para títulos y subtítulos (HEX)', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='descripcion_detallada',
            field=models.TextField(blank=True, help_text='Párrafo informativo adicional que aparecerá en el cuerpo de la página', null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='imagen_banner',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para el encabezado', null=True, upload_to='sectores/banners/'),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='logo_sector',
            field=models.ImageField(blank=True, help_text='Logo o escudo específico del área', null=True, upload_to='sectores/logos/'),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='color_destacado',
            field=models.CharField(default='#1a2a40', help_text='Color de fondo (HEX)', max_length=7),
        ),
    ]
