# Generated by Django 5.2.7 on 2026-03-10 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_configuracionsector_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsector',
            options={},
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_contenido_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_contenido_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_titulo_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_titulo_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='nombre_pantalla',
            field=models.CharField(default=django.utils.timezone.now, help_text='Nombre que ve el operador', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='slug_pantalla',
            field=models.SlugField(default=django.utils.timezone.now, help_text='ID interno (ej: inicio, tramites)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_web', to='users.area'),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='color_destacado',
            field=models.CharField(default='#1a2a40', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='color_iconos',
            field=models.CharField(default='#1a2a40', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='color_texto_principal',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to='sectores/banners/'),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='logo_sector',
            field=models.ImageField(blank=True, null=True, upload_to='sectores/logos/'),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='subtitulo_portal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='titulo_portal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionsector',
            unique_together={('area', 'slug_pantalla')},
        ),
    ]
