# Generated by Django 5.2.7 on 2026-03-11 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_configuracionsector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_contenido_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_contenido_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_titulo_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='extra_titulo_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='galeria_1',
            field=models.ImageField(blank=True, null=True, upload_to='sectores/galeria/'),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='galeria_2',
            field=models.ImageField(blank=True, null=True, upload_to='sectores/galeria/'),
        ),
        migrations.AddField(
            model_name='configuracionsector',
            name='galeria_3',
            field=models.ImageField(blank=True, null=True, upload_to='sectores/galeria/'),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='nombre_pantalla',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='slug_pantalla',
            field=models.SlugField(max_length=100),
        ),
        migrations.CreateModel(
            name='AccesoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('url_destino', models.URLField(max_length=255)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='sectores/accesos/')),
                ('icono_clase', models.CharField(default='bi-link', help_text='Clase de Bootstrap Icon', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='portal.configuracionsector')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
