# Generated by Django 5.2.7 on 2026-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_configuracionsector_extra_contenido_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesodirecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
