# Generated by Django 5.2.7 on 2026-03-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_accesodirecto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_contenido_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_contenido_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_contenido_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_contenido_4',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_titulo_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_titulo_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_titulo_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='extra_titulo_4',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='galeria_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='galeria_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='galeria_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsector',
            name='texto_boton',
        ),
        migrations.AlterField(
            model_name='accesodirecto',
            name='icono_clase',
            field=models.CharField(default='bi-link', max_length=50),
        ),
        migrations.CreateModel(
            name='ComponenteSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Bloque de Texto'), ('imagen', 'Imagen Destacada'), ('video', 'Video (Link)'), ('contacto', 'Ficha de Contacto')], default='texto', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sectores/componentes/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='portal.configuracionsector')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
