# Generated by Django 5.2.7 on 2026-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_configuracionsector_extra_contenido_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentesector',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
