# Generated by Django 5.2.7 on 2026-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_componentesector_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentesector',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
