# Generated by Django 5.2.7 on 2026-04-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_componentesector_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Recordatorio')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Descripción o Nota')),
                ('fecha_actual', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_designada', models.DateTimeField(help_text='Fecha en la que debe cumplirse el recordatorio', verbose_name='Fecha del Recordatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('completada', models.BooleanField(default=False, verbose_name='¿Completada?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota y Recordatorio',
                'verbose_name_plural': 'Notas y Recordatorios',
                'ordering': ['-fecha_designada'],
            },
        ),
        migrations.CreateModel(
            name='ArchivadorImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='notas/evidencias/%Y/%m/%d/', verbose_name='Imagen Adjunta')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='portal.notarecordatorio')),
            ],
            options={
                'verbose_name': 'Imagen de Nota',
                'verbose_name_plural': 'Archivador de Imágenes',
            },
        ),
    ]
