# Generated by Django 5.2.7 on 2026-04-30 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_notarecordatorio_archivadorimagen'),
        ('users', '0003_subarea_operadormunicipal_subarea_puesto_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsector',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_subarea', to='users.subarea'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_subarea', to='users.subarea'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_subarea', to='users.subarea'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_area', to='users.area'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_puesto', to='users.puesto'),
        ),
    ]
