# Generated by Django 5.2.7 on 2026-05-29 01:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_configuracionsector_subarea_contacto_subarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentesector',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsector',
            name='descripcion_detallada',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
