# Generated by Django 5.2.7 on 2026-01-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentas',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_renta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tasa', models.CharField(max_length=100)),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to='users.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivosRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='hacienda/comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='hacienda.rentas')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudHabilitacionComercial',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercio', models.CharField(max_length=200)),
                ('rubro', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
                ('direccion_local', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observacion_admin', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.operadormunicipal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
