# Generated by Django 5.2.7 on 2026-03-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventossociales',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
