# Generated by Django 5.2.7 on 2026-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_reclamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultassociales',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AlterModelOptions(
            name='reclamo',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AddField(
            model_name='consultassociales',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultassociales',
            name='respuesta_municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='respuesta_municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
