# Generated by Django 5.2.7 on 2026-03-30 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_consultassociales_options_and_more'),
        ('users', '0002_operadormunicipal_operador_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultassociales',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_recibidas', to='users.area', verbose_name='Área de destino'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_recibidos', to='users.area', verbose_name='Área de destino'),
        ),
        migrations.AlterField(
            model_name='consultassociales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_consultas', to=settings.AUTH_USER_MODEL),
        ),
    ]
