# Generated by Django 5.2.7 on 2026-04-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_consultassociales_area_destino_reclamo_area_destino_and_more'),
        ('users', '0003_subarea_operadormunicipal_subarea_puesto_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultassociales',
            name='subarea_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_recibidas', to='users.subarea', verbose_name='Sub-Área de destino'),
        ),
        migrations.AddField(
            model_name='eventossociales',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sociales', to='users.area'),
        ),
        migrations.AddField(
            model_name='eventossociales',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sociales', to='users.subarea'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='subarea_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_recibidos', to='users.subarea', verbose_name='Sub-Área de destino'),
        ),
    ]
