# Generated by Django 5.2.7 on 2026-01-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastros',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_catastro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_catastro', models.CharField(max_length=50, unique=True, verbose_name='Número de Catastro / Padrón')),
                ('nomenclatura', models.CharField(blank=True, help_text='Datos técnicos del lote/manzana', max_length=100)),
                ('direccion_inmueble', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Catastro',
                'verbose_name_plural': 'Catastros',
            },
        ),
        migrations.CreateModel(
            name='ArchivosCatastro',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ej: Plano de Mensura, Escritura PDF', max_length=100)),
                ('archivo', models.FileField(upload_to='territorio/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('catastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='territorio.catastros')),
            ],
        ),
    ]
