# Generated by Django 5.2.7 on 2025-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'managed': True, 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticia'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_principal',
            field=models.ImageField(blank=True, db_column='imagen', null=True, upload_to='noticia/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
    ]
