# Generated by Django 5.1.7 on 2025-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastros',
            name='nombre_propietario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
