# Generated by Django 5.1.7 on 2025-10-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_catastros_nombre_propietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True},
        ),
    ]
