# Generated by Django 5.2.7 on 2025-10-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_noticia_options_alter_noticia_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultassociales',
            options={'managed': True},
        ),
    ]
