# Generated by Django 5.2.7 on 2026-01-08 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_consultassociales_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHabilitacionComercial',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=20)),
                ('direccion_comercial', models.TextField()),
                ('rubro', models.CharField(max_length=100)),
                ('tipo_puesto', models.CharField(choices=[('fijo', 'Puesto fijo'), ('ambulante', 'Puesto ambulante'), ('feria', 'Puesto en feria'), ('otro', 'Otro')], max_length=20)),
                ('superficie_m2', models.DecimalField(decimal_places=2, help_text='Superficie del puesto en metros cuadrados', max_digits=6)),
                ('horario_funcionamiento', models.CharField(max_length=100)),
                ('dni_frente', models.FileField(blank=True, null=True, upload_to='habilitaciones/documentos/dni/')),
                ('constancia_cuit', models.FileField(blank=True, null=True, upload_to='habilitaciones/documentos/cuit/')),
                ('habilitacion_anterior', models.FileField(blank=True, null=True, upload_to='habilitaciones/documentos/habilitaciones_previas/')),
                ('croquis_puesto', models.FileField(blank=True, null=True, upload_to='habilitaciones/documentos/croquis/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('observacion_admin', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Solicitud de habilitación comercial',
                'verbose_name_plural': 'Solicitudes de habilitación comercial',
                'db_table': 'solicitudes_habilitacion_comercial',
                'ordering': ['-fecha_solicitud'],
                'managed': True,
            },
        ),
    ]
