# Generated by Django 5.2.7 on 2026-01-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_solicitudhabilitacioncomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudhabilitacioncomercial',
            name='observacion_admin',
            field=models.TextField(blank=True, help_text='Observaciones del administrador', null=True),
        ),
    ]
