# Generated by Django 5.2.7 on 2026-01-12 21:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_solicitudhabilitacioncomercial_observacion_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=django_ckeditor_5.fields.CKEditor5Field(db_column='contenido', verbose_name='Texto'),
        ),
    ]
