# Generated by Django 5.2.7 on 2026-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_noticia_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='area',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
