# Generated by Django 5.2.7 on 2026-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_contacto_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'managed': True, 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='sector',
            field=models.CharField(choices=[('GENERAL', 'General / Municipalidad'), ('SOCIAL', 'Acción Social'), ('HACIENDA', 'Hacienda y Finanzas'), ('CULTURA', 'Cultura y Turismo'), ('DEPORTES', 'Deportes'), ('OBRAS', 'Obras Públicas')], db_column='sector', default='GENERAL', max_length=20, verbose_name='Sector de la Noticia'),
        ),
    ]
