# Generated by Django 5.2.7 on 2026-01-13 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_eventossociales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventossociales',
            options={'ordering': ['fecha_evento'], 'verbose_name': 'Evento Social', 'verbose_name_plural': 'Eventos Sociales'},
        ),
        migrations.AddField(
            model_name='eventossociales',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='fecha_evento',
            field=models.DateTimeField(verbose_name='Fecha y hora del evento'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_sociales/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='eventossociales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
