# Generated by Django 5.2.7 on 2026-01-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_eventossociales_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventossociales',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
    ]
