# Generated by Django 5.2.7 on 2026-01-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_eventossociales_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
