# Generated by Django 5.2.7 on 2026-01-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_contacto_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.AddField(
            model_name='perfil',
            name='area',
            field=models.CharField(choices=[('ADMIN_GRAL', 'Administrador General (Control Total)'), ('CATASTRO', 'Área de Catastro'), ('COMERCIO', 'Área de Habilitaciones Comerciales'), ('HACIENDA', 'Área de Rentas y Hacienda'), ('VISITANTE', 'Visitante / Ciudadano (Solo consulta)')], default='VISITANTE', help_text='Define a qué sección del sistema tiene acceso el usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_actualizacion_perfil',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
