# Generated by Django 5.2.7 on 2026-01-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_perfil_options_remove_perfil_rol_perfil_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.CharField(choices=[('ADMIN_GRAL', 'Administración General / Intendencia'), ('SISTEMAS', 'Soporte Técnico y Sistemas'), ('CATASTRO', 'Dirección de Catastro y Tierras'), ('COMERCIO', 'Habilitaciones Comerciales y Bromatología'), ('RENTAS', 'Rentas y Recaudación'), ('SOCIAL', 'Acción Social y Vivienda'), ('OBRAS', 'Obras Públicas y Planeamiento'), ('VISITANTE', 'Ciudadano / Consulta Externa (Solo Lectura)')], default='VISITANTE', help_text='Define a qué sección del sistema tiene acceso el usuario', max_length=20),
        ),
    ]
