# Generated by Django 5.2.7 on 2026-01-14 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_contacto_creado_por_contacto_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
