"""
Django settings for projecto_municipalidad project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k)=j$u$^3t15b3m2(bv!o33zg)zd_4%_=)+r(@+4e41uv(r)8q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tus Apps Municipales
    'users',      # Perfiles, Operadores, Áreas
    'portal',     # Noticias, Eventos, Contactos
    'hacienda',   # Rentas, Comercio
    'territorio', # Catastro
    'social',     # Acción Social, Eventos Sociales
    'core',       # Auditoría y Base
    'static',

    # Librerías de terceros
    'django_bootstrap5',
    'django_ckeditor_5', # Opcional, por si quieres subir fotos dentro del texto
]

# La configuración de CK5 es más detallada
# Configuración para CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 
            'fontFamily', 'fontSize', 'fontColor', '|',
            'numberedList', 'blockQuote', '|', 
            'uploadImage', 'insertImage', '|',
            'undo', 'redo'
        ],

        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Sans Unicode, Lucida Grande, sans-serif',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, Helvetica, sans-serif',
                'Verdana, Geneva, sans-serif'
            ]
        },

        'htmlSupport': {
            'allow': [
                {'name': '/.*/', 'attributes': True, 'classes': True, 'styles': True}
            ]
        },

        # 🔥 AGREGÁ SOLO ESTO
        'image': {
            'toolbar': [
                'imageStyle:alignLeft',
                'imageStyle:alignCenter',
                'imageStyle:alignRight',
                '|',
                'imageTextAlternative'
            ],
            'styles': [
                'alignLeft',
                'alignCenter',
                'alignRight'
            ]
        }
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|', 'bulletedList', 'numberedList', 'todoList'
        ],
        'toolbar': [
            'heading', '|', 
            'bold', 'italic', 'underline', 'strikethrough', 'code', 'subscript', 'superscript', '|',
            'fontColor', 'fontBackgroundColor', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'alignment', 'outdent', 'indent', '|',
            'insertTable', 'link', 'blockQuote', '|',
            'sourceEditing', 'removeFormat'
        ],
        'image': {
            'toolbar': ['imageTextAlternative', 'imageStyle:inline', 'imageStyle:block', 'imageStyle:side']
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Párrafo', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Título 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Título 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Título 3', 'class': 'ck-heading_heading3'},
            ]
        }
    }
}

# Ruta para subida de imágenes (CK5 la usa de forma distinta pero es bueno definirla)
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_upload_file" # Opcional: usaremos el predeterminado si prefieres


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projecto_municipalidad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Fíjate en la COMA al final de la siguiente línea
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # ELIMINA cualquier línea que diga 'app1.context_processors...' aquí
            ],
        },
    },
]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'municipalidad',
        'USER': 'root',
        'PASSWORD': 'pablo897',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


WSGI_APPLICATION = 'projecto_municipalidad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# ESTA ES LA LÍNEA QUE TE FALTA:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
# Y que existan las carpetas de media si vas a subir fotos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py

# Nombre de la URL de tu vista de login (el que pusiste en urls.py)
LOGIN_URL = 'login' 

# Opcional: A dónde ir después de loguearse con éxito
LOGIN_REDIRECT_URL = 'bienvenida'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 1. Activamos el motor SMTP real para producción
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Datos del servidor de correo (Este ejemplo es para Gmail, pero cambia según el proveedor)
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True

# 3. Credenciales seguras (Idealmente leídas desde variables de entorno)
#import os
#EMAIL_HOST_USER = os.environ.get('EMAIL_USER')      # Ej: 'soporte.municipio@gmail.com'
#EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')  # Contraseña de aplicación o del servidor

# 4. El remitente que van a ver los operadores e invitados al recibir el mail
#DEFAULT_FROM_EMAIL = 'Soporte Municipal <soporte.municipio@gmail.com>'